// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QqgaTrQoCx3c_SJoMy9BPLDuShH9Aec',
    appId: '1:549252810544:web:49c080512b2de14154aaf5',
    messagingSenderId: '549252810544',
    projectId: 'food-a90d3',
    authDomain: 'food-a90d3.firebaseapp.com',
    storageBucket: 'food-a90d3.appspot.com',
    measurementId: 'G-7LF48Q4K5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hgfCZmsbq58GiR6--3nCE_4fo-Vn4Gk',
    appId: '1:549252810544:android:ed5f3e5635fd9b7454aaf5',
    messagingSenderId: '549252810544',
    projectId: 'food-a90d3',
    storageBucket: 'food-a90d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufgh0b2vzKNKy30VR6nUKqiAadtRBlcM',
    appId: '1:549252810544:ios:b88a98e5df88243c54aaf5',
    messagingSenderId: '549252810544',
    projectId: 'food-a90d3',
    storageBucket: 'food-a90d3.appspot.com',
    iosBundleId: 'com.example.clgProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufgh0b2vzKNKy30VR6nUKqiAadtRBlcM',
    appId: '1:549252810544:ios:5f74592eca13fef054aaf5',
    messagingSenderId: '549252810544',
    projectId: 'food-a90d3',
    storageBucket: 'food-a90d3.appspot.com',
    iosBundleId: 'com.example.clgProject.RunnerTests',
  );
}
